-- ============================================================================
-- Complete Landing Page Setup Migration
-- Run this if you want to reset and populate all landing sections with full data
-- ============================================================================

-- First, update the constraint to include navbar
ALTER TABLE landing_page_sections 
DROP CONSTRAINT IF EXISTS landing_page_sections_section_name_check;

ALTER TABLE landing_page_sections 
ADD CONSTRAINT landing_page_sections_section_name_check 
CHECK (section_name IN ('navbar', 'hero', 'features', 'how_to_use', 'reviews', 'pricing', 'footer'));

-- Delete existing data (optional - comment out if you want to keep existing data)
DELETE FROM landing_page_sections;

-- Insert all sections with complete data
INSERT INTO landing_page_sections (section_name, content, is_active, display_order) VALUES
('navbar', '{"brandName": "Mindfold", "links": [{"label": "Features", "href": "#features"}, {"label": "How It Works", "href": "#how-it-works"}, {"label": "Reviews", "href": "#reviews"}, {"label": "Pricing", "href": "#pricing"}], "loginText": "Log In", "signupText": "Get Started"}', true, 0),
('hero', '{"badge": "AI-Powered Mental Wellness", "title": "Transform Your Thoughts Into", "titleHighlight": "Wellness Insights", "subtitle": "Mindfold uses AI to analyze your daily journal entries, track 5 key mental health metrics, and connect you with professional therapists — all in one place.", "ctaPrimary": "Start Journaling Free", "ctaSecondary": "See How It Works", "stats": [{"value": "5", "label": "Wellness Metrics"}, {"value": "AI", "label": "Powered Insights"}, {"value": "24/7", "label": "Reflection Access"}]}', true, 1),
('features', '{"heading": "Everything You Need for", "headingHighlight": "Mental Wellness", "subtitle": "Powerful tools designed to help you understand yourself better and take control of your mental health journey.", "features": [{"icon": "BookOpen", "title": "Smart Journaling", "description": "Write daily entries and receive instant AI-generated reflections that help you understand your emotional patterns."}, {"icon": "Brain", "title": "Mental Health Metrics", "description": "Track 5 key metrics — mental health, happiness, accountability, stress, and burnout risk — scored from every entry."}, {"icon": "BarChart3", "title": "Visual Analytics", "description": "Beautiful graphs and charts that show your wellness trends over time, helping you spot patterns and celebrate progress."}, {"icon": "MessageCircle", "title": "Ask Your Journal", "description": "Chat with an AI that has read your journal. Ask questions like Why do I feel stressed on Mondays? and get real answers."}, {"icon": "Users", "title": "Therapist Connect", "description": "Browse verified therapists, book sessions, and share selected journal entries for more personalized professional support."}, {"icon": "Shield", "title": "Privacy First", "description": "Full control over what your therapist can see. Toggle visibility per entry, or disable sharing entirely."}]}', true, 2),
('how_to_use', '{"heading": "How", "headingHighlight": "Mindfold", "subtitle": "Four simple steps to start your mental wellness journey.", "steps": [{"icon": "UserPlus", "step": 1, "title": "Create Your Account", "description": "Sign up in seconds with just your name, email, and password. No credit card required to get started."}, {"icon": "PenLine", "step": 2, "title": "Write Daily Entries", "description": "Journal about your day in up to 2000 characters. Our clean editor makes it easy to express your thoughts."}, {"icon": "Sparkles", "step": 3, "title": "Get AI Insights", "description": "Our AI instantly analyzes your entry, generates a reflection, and scores 5 mental health metrics."}, {"icon": "TrendingUp", "step": 4, "title": "Track Your Progress", "description": "Watch your metrics improve over time. Ask your journal questions and connect with therapists for deeper support."}]}', true, 3),
('reviews', '{"heading": "Loved by", "headingHighlight": "Thousands", "subtitle": "See what our users and therapists are saying about Mindfold.", "reviews": [{"name": "Sarah M.", "role": "Daily Journaler", "content": "Mindfold has completely changed how I understand my emotions. The AI reflections are surprisingly insightful — it is like having a therapist in my pocket.", "rating": 5}, {"name": "James L.", "role": "Mental Health Advocate", "content": "The Ask Journal feature is a game-changer. I asked why I keep procrastinating and it gave me patterns I never noticed. Highly recommend!", "rating": 5}, {"name": "Dr. Emily R.", "role": "Licensed Therapist", "content": "As a therapist on the platform, I love how patients can share specific entries with me. The metrics give me a head start before each session.", "rating": 5}, {"name": "Michael K.", "role": "Software Engineer", "content": "The burnout risk metric literally saved me. I could see my scores declining and took action before things got worse. Simple but powerful.", "rating": 4}, {"name": "Priya S.", "role": "Graduate Student", "content": "I love the calendar view for my journal. Being able to look back at any day and see my metrics side by side is incredibly useful.", "rating": 5}, {"name": "Tom H.", "role": "Entrepreneur", "content": "The deep reflect mode blew my mind. It analyzed months of entries and found patterns in my stress that I had been completely blind to.", "rating": 5}]}', true, 4),
('pricing', '{"heading": "Simple, Transparent", "headingHighlight": "Pricing", "subtitle": "Choose the plan that works best for your wellness journey.", "plans": [{"name": "Basic", "price": 9.99, "features": ["Daily journaling", "AI reflections", "5 wellness metrics", "7-day history"], "highlighted": false}, {"name": "Intermediate", "price": 14.99, "features": ["Everything in Basic", "Ask your journal", "30-day history", "Therapist connect", "Priority support"], "highlighted": true}, {"name": "Advanced", "price": 24.99, "features": ["Everything in Intermediate", "Unlimited history", "Deep reflect mode", "Custom metrics", "API access"], "highlighted": false}]}', true, 5),
('footer', '{"brandDescription": "AI-powered mental health tracking and reflective journaling platform that transforms daily thoughts into measurable wellness insights.", "columns": [{"title": "Product", "links": [{"label": "Features", "href": "#features"}, {"label": "Pricing", "href": "#pricing"}, {"label": "How It Works", "href": "#how-it-works"}, {"label": "Reviews", "href": "#reviews"}]}, {"title": "Company", "links": [{"label": "About", "href": "#"}, {"label": "Privacy Policy", "href": "#"}, {"label": "Terms of Service", "href": "#"}, {"label": "Contact", "href": "#"}]}, {"title": "For Therapists", "links": [{"label": "Join as Therapist", "href": "/auth/therapist-register"}, {"label": "Therapist Guidelines", "href": "#"}, {"label": "Support", "href": "#"}]}], "copyright": "© 2026 Mindfold. All rights reserved."}', true, 6)
ON CONFLICT (section_name) DO UPDATE SET
  content = EXCLUDED.content,
  is_active = EXCLUDED.is_active,
  display_order = EXCLUDED.display_order;
